#!/bin/bash
# Test script for arrow key navigation in swebash

echo "==================================="
echo "Arrow Key Navigation Test for swebash"
echo "==================================="
echo ""
echo "This script will launch swebash. Follow these test steps:"
echo ""
echo "1. Basic Commands:"
echo "   Type: echo first"
echo "   Type: echo second"
echo "   Type: echo third"
echo ""
echo "2. Test History Navigation (Arrow Keys):"
echo "   Press ↑ (Up Arrow) - should show 'echo third'"
echo "   Press ↑ again - should show 'echo second'"
echo "   Press ↑ again - should show 'echo first'"
echo "   Press ↓ (Down Arrow) - should show 'echo second'"
echo "   Press ↓ again - should show 'echo third'"
echo "   Press ↓ again - should return to empty line"
echo ""
echo "3. Test Cursor Movement:"
echo "   Type: echo hello world"
echo "   Press ← (Left Arrow) multiple times"
echo "   Press Home or Ctrl-A - cursor jumps to start"
echo "   Press End or Ctrl-E - cursor jumps to end"
echo ""
echo "4. Test Editing:"
echo "   Type: echo test command"
echo "   Press Ctrl-A (start of line)"
echo "   Press Ctrl-K (clear to end)"
echo "   Verify line is cleared after cursor"
echo ""
echo "5. Test Hints:"
echo "   After running 'echo hello world'"
echo "   Type: echo h"
echo "   You should see 'ello world' in gray (hint)"
echo ""
echo "6. Test Exit:"
echo "   Type: exit"
echo "   Or press Ctrl-D on empty line"
echo ""
echo "==================================="
echo "Press Enter to launch swebash..."
read

# Run swebash
cd /home/adentic/swebash
./target/release/swebash

echo ""
echo "==================================="
echo "Test Complete!"
echo ""
echo "✓ If arrow keys navigated through history: SUCCESS"
echo "✗ If you saw ^[[A or similar: FAILURE"
echo "==================================="
